# Generated by Django 4.2.23 on 2025-07-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='savedproduct',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_saved_product_per_user'),
        ),
    ]
