# Generated by Django 4.2.23 on 2025-07-18 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_savedproduct_unique_saved_product_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productalert',
            name='saved_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='perfil.savedproduct'),
        ),
    ]
