# Generated by Django 4.2.23 on 2025-07-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_productalert_saved_product'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productalert',
            constraint=models.UniqueConstraint(fields=('user', 'saved_product'), name='unique_alert_per_saved_product'),
        ),
    ]
