# Generated by Django 4.2.23 on 2025-07-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_productalert_unique_alert_per_saved_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productalert',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
