# Generated by Django 4.2.23 on 2025-07-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productpricestatus_store_productprice_pricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='max_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productprice',
            name='min_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productprice',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productprice',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
